### PR TITLE
Fibonacci Sequence using iterative method

### PR DESCRIPTION
**Pull request by Eshan2203**

### CODE REVIEW

**Comment by koluacik** [comment]
Hi, and thanks for your contribution! Can you please include implementation in a seperate file so that others can still see the original code and work on that, please?

**Comment by Eshan2203** [comment]
Sorry i don' t get what you want to say, Can i send you PR,  making a separate folder for Fibonacci sequence code that i implemented.

**Comment by koluacik** [comment]
I think there is no need for a seperate folder, you can create a new file with a unique name like fibonacci_Eshan2203.py on the root directory of the repository.

**Comment by Eshan2203** [comment]
Ok i send you PR wait ?

**Comment by Eshan2203** [comment]
Done you can check now

**Comment by koluacik** [comment]
Done, happy hacking!

**Pull request merged**
